- project:
    templates:
      - openstackclient-plugin-jobs
      - check-requirements
      - publish-openstack-docs-pti
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - release-notes-jobs-python3
    check:
      jobs:
        - python-troveclient-tempest-neutron-src
        - openstack-tox-lower-constraints
        - trove-functional-mysql
    gate:
      queue: trove
      jobs:
        - python-troveclient-tempest-neutron-src

        - openstack-tox-lower-constraints
        - trove-functional-mysql
- job:
    name: python-troveclient-tempest-neutron-src
    parent: devstack-tempest
    timeout: 7800
    required-projects:
      - openstack-dev/devstack
      - openstack-infra/devstack-gate
      - openstack/ara
      - openstack/neutron
      - openstack/python-troveclient
      - openstack/trove
      - openstack/trove-dashboard
      - openstack/tempest
      - openstack/trove-tempest-plugin
    vars:
      tox_envlist: full
      devstack_localrc:
        TEMPEST_PLUGINS: /opt/stack/trove-tempest-plugin
      devstack_plugins:
        trove: git://git.openstack.org/openstack/trove

